AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  TodoListApi

  Sample SAM Template for TodoListApi

Globals:
  Function:
    Timeout: 3

Resources:
  ItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        GetItems:
          Type: Api
          Properties:
            Path: /items
            Method: get
        PostItem:
          Type: Api
          Properties:
            Path: /items
            Method: post
        PutItem:
          Type: Api
          Properties:
            Path: /items
            Method: put
        DeleteItem:
          Type: Api
          Properties:
            Path: /items
            Method: delete
Outputs:
  ItemsApi:
    Description: "API Gateway endpoint URL for Prod stage for Items function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/"
  ItemsFunction:
    Description: "Items Lambda Function ARN"
    Value: !GetAtt ItemsFunction.Arn
  ItemsFunctionIamRole:
    Description: "Implicit IAM Role created for Items function"
    Value: !GetAtt ItemsFunctionRole.Arn
